apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-ml-workspace

bases:
- ../../../../common/team-rolebindings/
- ../../../../common/jobs/installplan-approver/
- github.com/claudiol/manuela-dev//operator_subscriptions/seldon?ref=manuela-1.3
# if included here, the install will fail because kustomize will change the namespace from openshift-operators to manuela-ml-workspace
#- github.com/sa-mw-dach/manuela-dev//operator_subscriptions/opendatahub?ref=manuela-1.3

resources:
- manuela-ml-workspace-namespace.yaml
- manuela-ml-workspace-operatorgroup.yaml
